name: "Run Linter"
on: [pull_request]
jobs:
  Run-Linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ZedThree/clang-tidy-review@v0.7.0
        id: review
      # If there are any comments, fail the check
      - if: steps.review.outputs.total_comments > 0
        run: exit 1